import { Category, Language } from "./types";
import { Coffee, Bus, Receipt, ShoppingBag, Activity, GraduationCap, Film, CircleDollarSign, Briefcase, ArrowRightLeft, Wallet } from 'lucide-react';

export const CURRENCY_SYMBOL = 'Rs.';

export const TRANSLATIONS = {
  EN: {
    dashboard: "Dashboard",
    insights: "Insights",
    settings: "Settings",
    back: "Back",
    totalBalance: "Total Balance",
    received: "Received",
    expense: "Expense",
    recentActivity: "Recent Activity",
    noTransactions: "No transactions yet.",
    addFirst: "Tap + to add your first expense.",
    addTransaction: "Add Transaction",
    manual: "Manual",
    voice: "Voice",
    sms: "SMS",
    amount: "Amount",
    category: "Category",
    note: "Note",
    save: "Save",
    listening: "Listening...",
    tapToSpeak: "Tap to Speak",
    analyzing: "Analyzing...",
    trySaying: "Try saying:",
    exampleVoice: "\"500 ki chai peeli\"",
    parseSms: "Parse SMS",
    pasteSms: "Paste transaction SMS here...",
    uploadScreenshot: "Upload Screenshot",
    uploadScreenshotDesc: "Upload a banking screenshot to auto-extract and categorize expenses.",
    parseScreenshot: "Parse Screenshot",
    spendingAnalysis: "Spending Analysis",
    totalSpent: "Total Spent",
    categoryBreakdown: "Category Breakdown",
    exportData: "Export Data",
    downloadCsv: "Download CSV",
    downloadPdf: "Download PDF",
    dangerZone: "Danger Zone",
    clearData: "Clear All Data",
    language: "Language",
    voiceShortcuts: "Voice Shortcuts",
    enabled: "Enabled",
    about: "About",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    last30Days: "30 Days",
    thisYear: "This Year",
    allTime: "All",
    deleteConfirm: "Delete this transaction?",
    clearConfirm: "ARE YOU SURE? This will delete all your transaction history.",
    proTip: "Pro Tip",
    voiceTip: "Hands full? Just say:",
    voiceCommand: "\"Hey Google, tell Apna Hisab I spent 500 on lunch\"",
    installApp: "Install App",
    installDesc: "Add to home screen for offline use"
  },
  UR: {
    dashboard: "Jaiza",
    insights: "Tafseel",
    settings: "Settings",
    back: "Wapis",
    totalBalance: "Kul Raqam",
    received: "Aamdani",
    expense: "Kharcha",
    recentActivity: "Haaliya Activity",
    noTransactions: "Koi record nahi.",
    addFirst: "+ dabain aur kharcha shamil karein.",
    addTransaction: "Naya Hisaab",
    manual: "Likhein",
    voice: "Bol kar",
    sms: "SMS",
    amount: "Raqam",
    category: "Mad / Category",
    note: "Tafseel",
    save: "Save Karein",
    listening: "Sun raha hoon...",
    tapToSpeak: "Bolne ke liye dabain",
    analyzing: "Samajh raha hoon...",
    trySaying: "Ye bol kar check karein:",
    exampleVoice: "\"500 ki chai peeli\"",
    parseSms: "SMS Check Karein",
    pasteSms: "Bank SMS yahan paste karein...",
    uploadScreenshot: "Screenshot Upload Karein",
    uploadScreenshotDesc: "Banking screenshot upload karein aur kharchon ko auto categorize karein.",
    parseScreenshot: "Screenshot Parse Karein",
    spendingAnalysis: "Kharchon ka Jaiza",
    totalSpent: "Kul Kharcha",
    categoryBreakdown: "Kharcha Kahan Hua?",
    exportData: "Data Nikalein",
    downloadCsv: "CSV Download (Excel)",
    downloadPdf: "PDF Download (Print)",
    dangerZone: "Khatra",
    clearData: "Sara Data Delete Karein",
    language: "Zaban / Language",
    voiceShortcuts: "Awazi Control",
    enabled: "On Hai",
    about: "App ke baaray mein",
    thisMonth: "Is Mahinay",
    lastMonth: "Pichle Mahinay",
    last30Days: "30 Din",
    thisYear: "Is Saal",
    allTime: "Sara",
    deleteConfirm: "Kya ye delete kardein?",
    clearConfirm: "KYA AAP SURE HAIN? Sara purana hisaab hamesha ke liye delete hojayega.",
    proTip: "Mashwara",
    voiceTip: "Busy hain? Bas ye bolein:",
    voiceCommand: "\"Hey Google, Apna Hisab ko batao 500 ka khana khaya\"",
    installApp: "App Install Karein",
    installDesc: "Screen par icon lagane ke liye"
  }
};

export const CATEGORIES: { id: Category; label: { EN: string; UR: string }; color: string; icon: any; type: 'EXPENSE' | 'INCOME' | 'BOTH' }[] = [
  // Expenses
  { id: 'Food', label: { EN: 'Food & Chai', UR: 'Khana Peena' }, color: '#ef4444', icon: Coffee, type: 'EXPENSE' }, 
  { id: 'Transport', label: { EN: 'Transport', UR: 'Sawaari' }, color: '#f97316', icon: Bus, type: 'EXPENSE' }, 
  { id: 'Bills', label: { EN: 'Bills', UR: 'Bills' }, color: '#eab308', icon: Receipt, type: 'EXPENSE' }, 
  { id: 'Shopping', label: { EN: 'Shopping', UR: 'Khareedari' }, color: '#3b82f6', icon: ShoppingBag, type: 'EXPENSE' }, 
  { id: 'Health', label: { EN: 'Health', UR: 'Sehat' }, color: '#ec4899', icon: Activity, type: 'EXPENSE' }, 
  { id: 'Education', label: { EN: 'Education', UR: 'Taleem' }, color: '#8b5cf6', icon: GraduationCap, type: 'EXPENSE' }, 
  { id: 'Entertainment', label: { EN: 'Fun', UR: 'Tafreeh' }, color: '#10b981', icon: Film, type: 'EXPENSE' }, 
  
  // Income specific
  { id: 'Salary', label: { EN: 'Salary', UR: 'Tankhwa' }, color: '#059669', icon: Wallet, type: 'INCOME' },
  { id: 'Business', label: { EN: 'Business', UR: 'Karobar' }, color: '#0ea5e9', icon: Briefcase, type: 'INCOME' },
  
  // Both/Misc
  { id: 'Transfer', label: { EN: 'Transfer', UR: 'Transfer' }, color: '#6366f1', icon: ArrowRightLeft, type: 'BOTH' },
  { id: 'Other', label: { EN: 'Other', UR: 'Deegar' }, color: '#6b7280', icon: CircleDollarSign, type: 'BOTH' },
];

export const MOCK_SMS_TEMPLATES = [
  "Trx ID: 88291. You have paid Rs. 1,250 to FoodPanda via SadaPay on 12-05. Bal: 45,000.",
  "JazzCash: You have transferred Rs. 500 to 0300-1234567 for Mobile Load.",
  "Credit Alert: Rs. 50,000 credited to your HBL Account from XYZ Corp Salary.",
  "POS Transaction of PKR 4500 at Al-Fatah Store on your HBL Card ending 1234."
];